app/urls.py
from django.urls import path
from . import views
from usuarios.views import perfil

urlpatterns = [
    path('', views.index, name="index"),
    path('meus_materiais/', views.meus_materiais, name="meus_materiais"),
    path('sobre/', views.sobre, name="sobre"),
    
    path('editar/<int:id_material>/', views.editar_material, name='editar_material'),
    path('deletar/<int:id_material>/', views.deletar_material, name='deletar_material'),
    path('visualizar/<int:id_material>/', views.visualizar_material, name='visualizar_material'),
    path('perfil/', perfil, name="perfil"),
    path('buscar/', views.buscar_materiais, name='buscar_materiais'),
    path('salvar/<int:id_material>/', views.salvar_material, name='salvar_material'),
    
    path('configuracoes/', views.configuracoes, name="configuracoes"),
    path('mat_compart/', views.mat_compart, name="mat_compart"),
    path('avaliacao_receb/', views.avaliacao_receb, name="avaliacao_receb"),
    path('histor_pesq/', views.histor_pesq, name="histor_pesq"),
    path('permissoes_avali/', views.permissoes_avali, name="permissoes_avali"),
    path('curtir_material/<int:material_id>/', views.curtir_material, name='curtir_material'),
    path('material/<int:material_id>/', views.material_detalhe, name='material_detalhe'),
    path('material/<int:material_id>/comentar/', views.comentar, name='comentar'),
    path('buscar_usuarios/', views.buscar_usuarios, name='buscar_usuarios'),
    
    path('convites/', views.convites, name='convites'),
    path('convites/<int:convite_id>/responder/', views.responder_convite, name='responder_convite'),
    path('material/<int:material_id>/publicar', views.publicar_material, name='publicar_material'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
from django.conf import settings
from django.utils import timezone

class Material(models.Model):
    SLIDE = 'SL'
    VIDEO = 'VD'
    DOCUMENTO = 'DC'
    TIPO_CHOICES = [
        (SLIDE, 'Slide'),
        (VIDEO, 'Vídeo'),
        (DOCUMENTO, 'Documento'),
    ]
    STATUS_CHOICES = [
        ('rascunho', 'Rascunho'),
        ('aguardando', 'Aguardando colaboração'),
        ('publicado', 'Publicado'),
    ]
    
    autor = models.CharField(max_length=100)
    descricao = models.TextField(max_length=100)
    titulo = models.CharField(max_length=200)
    tipo = models.CharField(
        max_length=2,
        choices=TIPO_CHOICES,
        default=DOCUMENTO,
    )
    arquivo = models.FileField(upload_to='meus_materiais/')
    
    avaliacoes_habilitadas = models.BooleanField(default=False)

    colaboracao_habilitada = models.BooleanField(default=False)
    colaboradores_pendentes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="convites_recebidos",
        blank=True
    )
    colaboradores_confirmados = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="colaboracoes_confirmadas",
        blank=True
    )
    
    curtidas = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='materiais_curtidos',
        blank=True
    )

    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='rascunho')
    data_compartilhado = models.DateTimeField(null=True, default=timezone.now)

    def __str__(self):
        return self.titulo
    
    
class MaterialSalvo(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    material = models.ForeignKey('Material', on_delete=models.CASCADE)
    data_salvo = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario.username} salvou {self.material.titulo}"


class Comentario(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE, related_name='comentarios')
    texto = models.TextField()
    curtidas = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comentarios_curtidos', blank=True)
    criado_em = models.DateTimeField(auto_now_add=True)

    
class HistoricoPesquisa(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    termo = models.CharField(max_length=255)
    url_resultado = models.URLField()
    data_pesquisa = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.termo} ({self.data_pesquisa.strftime('%d/%m/%Y %H:%M')})"
    
class ConviteColaboracao(models.Model):
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    remetente = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='convites_enviados'
    )
    destinatario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='convites_recebidos_detalhados'  # <-- nome único
    )
    status = models.CharField(max_length=20, choices=[
        ('pendente', 'Pendente'),
        ('aceito', 'Aceito'),
        ('negado', 'Negado')
    ], default='pendente')
    data_envio = models.DateTimeField(auto_now_add=True)
    data_resposta = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Convite de {self.remetente.username} para {self.destinatario.username} - {self.status}"

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'responsive.css' %}">
    <title>{% block title %}Biblioteca Virtual Alexandria{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
  <header class="navbar d-flex align-items-center px-4">
    <nav class="navbar-center w-100 d-flex justify-content-between align-items-center">
      <!-- Ícones centralizados -->
      <ul id="navMenu" class="nav justify-content-center mx-auto">
        <li class="nav-item">
          <a href="{% url 'index' %}" class="nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Início">
            <i class="bi bi-house"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'meus_materiais' %}" class="nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Meus Materiais">
            <i class="bi bi-folder"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'sobre' %}" class="nav-link" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sobre o Sistema">
            <i class="bi bi-code-slash"></i>
          </a>
        </li>
      </ul>

      <!-- Dropdown do usuário à direita -->
      <div class="dropdown">
        <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-person-circle"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="{% url 'editar_perfil' %}"><i class="bi bi-person-fill"></i> Área do Usuário</a></li>
          <li><a class="dropdown-item" href="{% url 'configuracoes' %}"><i class="bi bi-gear-fill"></i> Configurações</a></li>
          <li>
            <form action="{% url 'logout' %}" method="POST" style="margin: 0;">
              {% csrf_token %}
              <button type="submit" class="dropdown-item" style="border: none; font-weight: 650;">
                <i class="bi bi-box-arrow-right"></i> Sair
              </button>
            </form>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <div class="wrapper">
    <main>
      <div class="content">
          {% if messages %}
            <div class="message-container">
              {% for message in messages %}
                <div class="alert {{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            </div>
          {% endif %}

          {% block content %}{% endblock %}
          {% block header %}{% endblock %}
      </div>
    </main>

    <footer class="footer">
      <div style="max-width: 1000px; margin: auto; display: flex; flex-wrap: wrap; justify-content: space-between;">
      <div style="flex:1; min-width:200px;">
        <h3 style="font-family: Georgia; font-weight: bold;">Biblioteca Virtual Alexandria</h3>
        <p style="font-family: Georgia;">Explore. Leia. Descubra.</p>
      </div>
      <div style="flex:1; min-width:200px;">
        <h3 style="font-family: Georgia; font-weight: bold">Contato</h3>
        <p style="font-family: Georgia;">Email: contato@biblioteca.com</p>
        <p style="font-family: Georgia;">WhatsApp: (84) 99999-9999</p>
      </div>
      <div style="flex:1; min-width:200px;">
        <h3 style="font-family: Georgia; font-weight: bold">Frase do Dia</h3>
        <p style="font-family: Georgia;">“Só sei que nada sei.” – Sócrates</p>
      </div>
      </div>
      <hr style="margin:20px 0; border-color:#7f8c8d;">
      <p style="text-align:center; font-family: Georgia; margin-top: 45px;">&copy; 2025 Biblioteca Alexandria</p>
    </footer>
  </div>

  <script>
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
  [...tooltipTriggerList].map(el => new bootstrap.Tooltip(el));
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
</body>
</html>

app/templates/busca.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Resultados da busca{% endblock %}

{% block content %}
<div class="search-bar-busca">
    <form method="get" action="{% url 'buscar_materiais' %}">
        <input type="text" name="q" placeholder="Digite o título, autor ou palavra-chave...">
        <button type="submit" class="search-btn-busca" aria-label="Pesquisar"></button>
    </form>
</div>

<h3 style="color: white; margin-bottom: 30px;">Resultados da busca para "{{ query }}"</h3>

<div class="materiais-container">
    {% for material in materiais %}
    <div class="material-resultado">
        <div class="card-content">
            <h3>Título: {{ material.titulo }}</h3>
            <p class="autor"><strong>Autor:</strong> {{ material.autor }}</p>
            <p class="descricao"><strong>Descrição:</strong> {{ material.descricao }}</p>
            <div class="meta-info">
                <span class="tipo">{{ material.get_tipo_display }}</span>
            </div>
        </div>
        <div class="card-buttons">
            <button type="button" class="btn-abrir-modal" data-bs-toggle="modal" data-bs-target="#modalMaterial{{ material.id }}">
                Abrir
            </button>
            <form action="{% url 'salvar_material' material.id %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn-salvar">Salvar</button>
            </form>
        </div>
    </div>
    {% empty %}
    <p>Nenhum material encontrado.</p>
    {% endfor %}
</div>

{% for material in materiais %}
<!-- MODAL -->
<div class="card-actions">
    <div class="modal fade" id="modalMaterial{{ material.id }}" tabindex="-1" aria-labelledby="modalLabel{{ material.id }}" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel{{ material.id }}">
                        <a style="color: rgb(142, 136, 151); font-size: 25px;" class="icon-brand">
                            Material: {{ material.titulo }}
                        </a>
                    </h5>
                    <button style="color: rgb(142, 136, 151); font-size: 18px; margin-right: 10px;" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                </div>

                <div class="modal-body">
                    <div class="d-flex flex-wrap gap-4 justify-content-center">
                        <!-- Coluna única com imagem e botão -->
                        <div class="col-md-5 d-flex flex-column align-items-center">
                            <img src="/static/img/imagem-ilustrativa.png" alt="Imagem ilustrativa" class="img-fluid rounded mb-3" style="max-height: 200px; object-fit: cover;">

                            <a href="{{ material.arquivo.url }}" target="_blank" class="btn btn-outline-secondary mb-3">
                                📄 Visualizar Arquivo
                            </a>

                            {% if material.avaliacoes_habilitadas %}
                            <form method="POST" action="{% url 'curtir_material' material.id %}">
                                {% csrf_token %}
                                <button style="padding-left: 36px; padding-right: 36px;" type="submit" class="btn btn-outline-danger">
                                    {% if user in material.curtidas.all %}
                                    💔 Descurtir
                                    {% else %}
                                    ❤️ Curtir
                                    {% endif %}
                                    ({{ material.curtidas.count }})
                                </button>
                            </form>
                            {% endif %}
                        </div>

                        {% if material.avaliacoes_habilitadas %}
                        <!-- Coluna direita com formulário de comentário -->
                        <div class="col-md-6">
                            <form method="POST" action="{% url 'comentar' material.id %}">
                                {% csrf_token %}
                                <textarea name="comentario" class="form-control mb-2" rows="3" placeholder="Deixe seu comentário"></textarea>
                                <button type="submit" class="btn btn-comentenv">Enviar Comentário</button>
                            </form>
                        </div>
                        {% endif %}
                    </div>

                    {% if material.avaliacoes_habilitadas %}
                    <!-- Comentários recebidos -->
                    <h3 class="text-center mt-4" style="font-size: 19px; color: rgb(131, 130, 130);">
                        <hr>Comentários Recebidos<hr>
                    </h3>
                    <div class="comentarios-grid d-flex flex-wrap justify-content-center gap-3 mt-3">
                        {% for comentario in material.comentarios.all %}
                        <div class="comentario-card alert alert-secondary" style="flex: 0 1 calc(50% - 1rem); min-width: 250px;">
                            <p style="color: rgb(148, 144, 144);">Usuário: {{ comentario.autor }}</p>
                            <p style="color: rgb(148, 144, 144);">Comentário: {{ comentario.texto }}</p>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <!-- Mensagem quando avaliações não estão habilitadas -->
                    <div class="text-center mt-4">
                        <p style="color: rgb(148, 144, 144); font-style: italic;">
                            Este material não está disponível para avaliação.
                        </p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

app/templates/deletar_material.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container-mat">
    <div class="delete-material">
        <h2>Deletar Material</h2>
        <p>Você tem certeza que quer deletar o material "{{ material }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Sim, deletar</button>
            <a href="{% url 'index' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</main>
{% endblock %}

app/templates/editar_material.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container-mat">
    <div class="edit-material">
        <h2>Editar Material</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </div>
</main>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Início{% endblock %}

{% block content %}
<main class="main-content">
    <h1>
        <!-- Logo/Brand -->
        <a class="icon-brand">
            Biblioteca Alexandria
        </a>
    </h1>
    <div class="search-bar">
        <form method="get" action="{% url 'buscar_materiais' %}">
            <input type="text" name="q" placeholder="Digite o título, autor ou palavra-chave...">
            <button type="submit" class="search-btn" aria-label="Pesquisar"></button>
        </form>
    </div>
</main>
{% endblock %}

<!-- <h1> 
    <a class="icon-brand">
            Estudaí
        </a>
    </h1>
   <h4 style="color: white; font-family: Georgia;">Tecnologia Educacional e Colaboração Acadêmica.</h4>
-->

app/templates/material_detalhe.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="d-flex gap-2 mb-3">
    <form method="POST" action="{% url 'curtir_material' material.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger btn-sm">
            {% if user in material.curtidas.all %}
                💔 Descurtir
            {% else %}
                ❤️ Curtir
            {% endif %}
            ({{ material.curtidas.count }})
        </button>
    </form>
    <button class="btn btn-outline-secondary btn-sm" disabled>Comentar</button>
</div>

{% if material.avaliacoes_habilitadas %}
    <form method="POST" action="{% url 'comentar' material.id %}">
        {% csrf_token %}
        <textarea name="comentario" class="form-control mt-2" rows="3" placeholder="Deixe seu comentário"></textarea>
        <button type="submit" class="btn btn-primary mt-2">Enviar</button>
    </form>

    {% for comentario in material.comentarios.all %}
        <div class="card mt-4">
            <div class="card-header">
                <h4 class="mb-0">Avaliações e Comentários</h4>
            </div>
            <div class="card-body">
                <div class="alert alert-secondary">
                    <strong>{{ comentario.autor }}:</strong> {{ comentario.texto }}
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="alert alert-warning d-flex align-items-center mt-3" role="alert">
        <i class="bi bi-exclamation-triangle-fill me-2"></i> Esses recursos estarão disponíveis após salvar o material.
    </div>
{% endif %}
{% endblock %}

app/templates/meus_materiais.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Meus Materiais{% endblock %}

{% block content %}
<div class="page-wrapper">

  <h1 class="page-title">
    <a class="icon-brand">Meus Materiais</a>
  </h1>

<!-- MATERIAIS SALVOS -->
<div class="section-container">
    <h2 class="section-title">Materiais Salvos</h2>
    <div class="materiais-tipos">
        <!-- Vídeos -->
        <div class="tipo-bloco">
            <h2>Vídeos</h2>
            <div class="materiais-criados-grid">
                {% for video in videos_salvos %}
                <div class="material-item">
                    <h3>{{ video.material.titulo }}</h3>
                    <p><strong>Autor:</strong> {{ video.material.autor }}</p>
                    <p><strong>Descrição:</strong> {{ video.material.descricao }}</p>
                    <a href="{% url 'visualizar_material' video.material.id %}" class="btn visualizar">Visualizar Material</a>
                </div>
                {% empty %}
                <p>Não há vídeos salvos.</p>
                {% endfor %}
            </div>
        </div>

        <!-- Slides -->
        <div class="tipo-bloco">
            <h2>Slides</h2>
            <div class="materiais-criados-grid">
                {% for slide in slides_salvos %}
                <div class="material-item">
                    <h3>{{ slide.material.titulo }}</h3>
                    <p><strong>Autor:</strong> {{ slide.material.autor }}</p>
                    <p><strong>Descrição:</strong> {{ slide.material.descricao }}</p>
                    <a href="{% url 'visualizar_material' slide.material.id %}" class="btn visualizar">Visualizar Material</a>
                </div>
                {% empty %}
                <p>Não há slides salvos.</p>
                {% endfor %}
            </div>
        </div>

        <!-- Documentos -->
        <div class="tipo-bloco">
            <h2>Documentos</h2>
            <div class="materiais-criados-grid">
                {% for documento in documentos_salvos %}
                <div class="material-item">
                    <h3>{{ documento.material.titulo }}</h3>
                    <p><strong>Autor:</strong> {{ documento.material.autor }}</p>
                    <p><strong>Descrição:</strong> {{ documento.material.descricao }}</p>
                    <a href="{% url 'visualizar_material' documento.material.id %}" class="btn visualizar">Visualizar Material</a>
                </div>
                {% empty %}
                <p>Não há documentos salvos.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<!-- MATERIAIS PUBLICADOS -->
<div class="section-container">
    <h2 class="section-title">Materiais Publicados</h2>
    <div class="materiais-grid">
        {% for material in page_obj %}
        <div class="material-card">
            <div class="card-content">
                <h3>{{ material.titulo }}</h3>
                <p class="autor"><strong>Autor:</strong> {{ material.autor }}</p>
                <p class="descricao"><strong>Descrição:</strong> {{ material.descricao }}</p>
                <div class="meta-info">
                    <span class="tipo">{{ material.get_tipo_display }}</span>
                </div>
            </div>
            
            <div class="card-actions">
                <a href="{% url 'visualizar_material' material.id %}" target="_blank" class="btn abrir">Abrir</a>
                <a href="{% url 'editar_material' material.id %}" class="btn editar">Editar</a>
                <form action="{% url 'deletar_material' material.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn deletar">Deletar</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Primeira</a>
                <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            {% endif %}

            <span class="current">
                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

<div class="section-container">
  <h2 class="section-title">
    Adicionar Material
  </h2>
  <button id="btnAdicionarMaterial" class="btn-adicionar-material">
    <span class="icon">➕</span> Adicione Novo Material
  </button>
  <!-- Formulário escondido inicialmente -->
  <div id="formAdicionarMaterial" style="display:none; margin-top:40px;">
    <div class="add-material">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Título -->
        <div class="form-row">
          <label for="{{ form.titulo.id_for_label }}" class="label-inline">Título:</label>
          <div class="input-inline">
            {{ form.titulo }}
          </div>
        </div>

        <!-- Descrição -->
        <div class="form-row">
          <label for="{{ form.descricao.id_for_label }}" class="label-inline">Descrição:</label>
          <div class="input-inline">
            {{ form.descricao }}
          </div>
        </div>

        <!-- Tipo e Arquivo lado a lado -->
        <div class="form-row">
          <div class="half-width">
            <label for="{{ form.tipo.id_for_label }}" class="label-inline">Tipo:</label>
            <div class="input-inline">
              {{ form.tipo }}
            </div>
          </div>
          <div class="half-width">
            <label for="{{ form.arquivo.id_for_label }}" class="label-inline">Arquivo:</label>
            <div class="input-inline">
              {{ form.arquivo }}
            </div>
          </div>
        </div>

        <!-- Permissões -->
        <h3 style="margin-bottom: 0px; margin-top: 20px; color: white; font-size: 16px; font-weight: 400; font-family: Arial, Helvetica, sans-serif;">
          Permissões:
        </h3>
        <div class="form-row">
          <div class="form-habit half-width">
            <label for="id_avaliacoes_habilitadas">Habilitar Avaliações:</label>
            <label class="switch">
              <input type="checkbox" name="avaliacoes_habilitadas" id="id_avaliacoes_habilitadas">
              <span class="slider"></span>
            </label>
          </div>

          <div class="form-habit half-width">
            <label for="id_colaboracao_habilitada">Habilitar Colaboração:</label>
            <label class="switch">
              <input type="checkbox" name="colaboracao_habilitada" id="id_colaboracao_habilitada">
              <span class="slider"></span>
            </label>
          </div>
        </div>

        <!-- Campo colaborador -->
        <div class="form-row" id="campoColaborador" style="margin-top: 10px;">
          <label for="{{ form.email_colaborador.id_for_label }}" class="label-inline">Email do colaborador:</label>
          <div class="input-inline">
            {{ form.email_colaborador }}
          </div>
        </div>

        <!-- Botão -->
        <div class="form-actions">
          <button type="submit">Criar Material</button>
        </div>
      </form>
    </div>
  </div>
</div>
   
<script>
document.addEventListener('DOMContentLoaded', function () {
    const btn = document.getElementById('btnAdicionarMaterial');
    const form = document.getElementById('formAdicionarMaterial');
    const colaboracaoCheckbox = document.getElementById('id_colaboracao_habilitada');
    const campoColaborador = document.getElementById('campoColaborador');

    // Mostrar/ocultar formulário
    btn.addEventListener('click', function () {
        form.style.display = (form.style.display === 'none') ? 'block' : 'none';
    });

    // Mostrar campo colaborador
    function toggleCampo() {
        campoColaborador.style.display = colaboracaoCheckbox.checked ? 'block' : 'none';
    }
    colaboracaoCheckbox.addEventListener('change', toggleCampo);
    toggleCampo();
});
</script>

</div>
{% endblock %}

app/templates/sobre.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sobre{% endblock %}

{% block content %}
<body>
    <main style="padding: 0px 15px;" class="sobre">
        <h1>
            <a class="icon-brand">
                Sobre a Biblioteca Virtual Alexandria
            </a>
        </h1>
        <div class="s_texto">
            <p>
                <strong>Bem-vindo à Biblioteca Virtual Alexandria!</strong>
            <p>
                Inspirada na lendária Biblioteca de Alexandria, o Sistema de Biblioteca Virtual é um software que tem como 
                objetivo centralizar e organizar os trabalhos acadêmicos em um repositório digital acessível online, 
                facilitando a consulta de qualquer lugar e a qualquer momento. 
                Nesta plataforma, objetiva-se democratizar e facilitar o acesso ao conhecimento através da vasta coleção de 
                documentos, relatórios, artigos e vídeos acadêmicos e recursos educacionais criados pelos alunos do campus 
                que sejam relevantes para seus estudos e interesses pessoais.
                Com uma interface amigável e recursos avançados de busca, os usuários podem facilmente encontrar e acessar os 
                materiais.
            <p>
                Junte-se a nós nessa jornada pelo conhecimento e compartilhe seus materiais na Biblioteca Virtual Alexandria!
            </p>
            <p>
                <strong>Equipe de Desenvolvimento:</strong> Luana Lima e João Victor, estudantes da turma de 2022 no curso Informática 
                para Internet/Instituto Federal de São Paulo do Potengi (IFRN-SPP).
            </p>
            
        </div>
    </main>
</body>
{% endblock %}